// Embeds the extension bundles from src/extensions/ into the vendored
// installer src/templates/shibumi.ts and records the resulting file's sha256
// in scripts/shibumi.lock.json. Scaffolding verifies that checksum before
// vendoring, and a test regenerates the payload to prove the committed file
// is current. Run after any change under src/extensions/:
//
//   bun run sync:extensions
//
// buildBundles/injectBundles are exported so the byte-identity test can
// regenerate in memory without writing.
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const EXTENSIONS_DIR = join(ROOT, "src", "extensions");
const TARGET = join(ROOT, "src", "templates", "shibumi.ts");
const LOCK_PATH = join(ROOT, "scripts", "shibumi.lock.json");

const START_MARKER = "// --- shibumi:extensions:start (generated by scripts/sync-extensions.ts; do not edit) ---";
const END_MARKER = "// --- shibumi:extensions:end ---";

interface ManifestHook {
  file: string;
  find: string;
  insert?: string;
  replace?: string;
}

interface Manifest {
  name: string;
  title: string;
  description: string;
  requires: "database" | null;
  dependsOn?: string[];
  env: string[];
  deps?: Record<string, string>;
  hooks?: ManifestHook[];
  rootSection: string;
  removeNote?: string;
}

function listFilesRecursively(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    // lstat, never stat: a symlink here would embed arbitrary host files
    // into the published bundle at sync time.
    const info = lstatSync(full);
    if (info.isSymbolicLink()) fail(`symlink not allowed in extension sources: ${full}`);
    if (info.isDirectory()) {
      results.push(...listFilesRecursively(full));
    } else {
      results.push(full);
    }
  }
  return results.sort();
}

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

export function buildBundles(extensionsDir = EXTENSIONS_DIR): unknown[] {
  const bundles: unknown[] = [];
  for (const name of readdirSync(extensionsDir).sort()) {
    const dir = join(extensionsDir, name);
    if (!statSync(dir).isDirectory()) continue;

    const manifestPath = join(dir, "manifest.json");
    if (!existsSync(manifestPath)) fail(`${name}: manifest.json missing`);
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
    if (manifest.name !== name) fail(`${name}: manifest name "${manifest.name}" does not match directory`);
    if (!manifest.title || !manifest.description) fail(`${name}: title and description are required`);
    if (manifest.requires !== "database" && manifest.requires !== null) {
      fail(`${name}: requires must be "database" or null`);
    }
    if (!manifest.rootSection?.startsWith("## ")) {
      fail(`${name}: rootSection must start with a "## " heading`);
    }
    for (const hook of manifest.hooks ?? []) {
      const kinds = [hook.insert, hook.replace].filter((value) => value !== undefined).length;
      if (!hook.file || !hook.find || kinds !== 1) {
        fail(`${name}: every hook needs file, find, and exactly one of insert or replace`);
      }
    }

    const filesDir = join(dir, "files");
    const files = existsSync(filesDir)
      ? listFilesRecursively(filesDir).map((path) => ({
          to: relative(filesDir, path),
          content: readFileSync(path, "utf8"),
        }))
      : [];
    if (files.length === 0) fail(`${name}: no files under files/`);

    const agentsSource = join(dir, "agents", `${name}.md`);
    if (!existsSync(agentsSource)) fail(`${name}: agents/${name}.md missing`);

    const migrationPath = join(dir, "migration.sql");
    const migration = existsSync(migrationPath) ? readFileSync(migrationPath, "utf8") : null;
    if (manifest.requires === "database" && migration === null) {
      fail(`${name}: requires database but has no migration.sql`);
    }

    bundles.push({
      name: manifest.name,
      title: manifest.title,
      description: manifest.description,
      requires: manifest.requires,
      ...(manifest.dependsOn && manifest.dependsOn.length > 0 ? { dependsOn: manifest.dependsOn } : {}),
      env: manifest.env ?? [],
      ...(manifest.deps && Object.keys(manifest.deps).length > 0 ? { deps: manifest.deps } : {}),
      files,
      hooks: manifest.hooks ?? [],
      migration,
      agentsFile: readFileSync(agentsSource, "utf8"),
      rootSection: manifest.rootSection,
      ...(manifest.removeNote ? { removeNote: manifest.removeNote } : {}),
    });
  }
  return bundles;
}

export function injectBundles(source: string, bundles: unknown[]): string {
  const start = source.indexOf(START_MARKER);
  const end = source.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) fail("markers not found in src/templates/shibumi.ts");
  const payload = JSON.stringify(JSON.stringify(bundles));
  return (
    source.slice(0, start + START_MARKER.length) +
    `\nconst EXTENSIONS_JSON = ${payload};\n` +
    source.slice(end)
  );
}

if (import.meta.main) {
  const bundles = buildBundles();
  const updated = injectBundles(readFileSync(TARGET, "utf8"), bundles);
  writeFileSync(TARGET, updated);
  const sha256 = createHash("sha256").update(updated).digest("hex");
  const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string };
  writeFileSync(
    LOCK_PATH,
    `${JSON.stringify(
      {
        version: pkg.version,
        extensions: bundles.map((bundle) => (bundle as { name: string }).name),
        sha256,
      },
      null,
      2
    )}\n`
  );
  console.log(`Embedded ${bundles.length} extension(s); lock updated (${sha256.slice(0, 12)}…).`);
}
